# Generated by Django 4.2.25 on 2025-11-09 20:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_usuario_groups_usuario_password_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialSeguimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_anterior', models.CharField(max_length=20, verbose_name='Estado Anterior')),
                ('estado_nuevo', models.CharField(choices=[('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], max_length=20, verbose_name='Nuevo Estado')),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('notas', models.TextField(blank=True, null=True, verbose_name='Notas de Seguimiento')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_seguimiento', to='home.pedido')),
                ('usuario_admin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Usuario Administrador')),
            ],
            options={
                'verbose_name': 'Historial de Seguimiento',
                'ordering': ['-fecha_cambio'],
            },
        ),
    ]
