# Generated by Django 4.2.25 on 2025-11-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedidos_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialseguimiento',
            name='estado_nuevo',
            field=models.CharField(choices=[('PEDIDO', 'Pedido'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], max_length=20, verbose_name='Nuevo Estado'),
        ),
    ]
