"""
Django settings for mundo_jardin project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
import dj_database_url


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/


LOGIN_URL = 'inicio_sesion:login'
# LOGIN_REDIRECT_URL ='/inicio_sesion/cambio_rol'
LOGIN_REDIRECT_URL = 'inicio_sesion:post_login_redirect'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'home',
    'adminpanel',
    'ventas_admin',
    'catalogo_admin',
    'clientes_admin',
    'registro_usuario',
    'inicio_sesion',
    'perfil',
    'pedidos_admin',
    'info_tienda',
    'carrito',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'mundo_jardin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'home.context_processors.productos_en_cesta',
            ],
        },
    },
]

STATIC_URL = 'static/'

# Dónde buscar archivos estáticos adicionales (como tu carpeta "static" global)
# Asegúrate de que tu carpeta de imágenes estáticas exista en el nivel superior de tu proyecto
STATICFILES_DIRS = [
    BASE_DIR / 'static', 
    # O, si la carpeta se llama 'imagenes_estaticas': BASE_DIR / 'imagenes_estaticas',
]
# DIRECTORIO DE RECOLECCIÓN (CLAVE PARA PRODUCCIÓN)
# Al ejecutar 'collectstatic', Django copiará todos los archivos estáticos aquí.
STATIC_ROOT = BASE_DIR / 'staticfiles_collect'

WSGI_APPLICATION = 'mundo_jardin.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# SECRET_KEY desde variable de entorno
SECRET_KEY = os.environ.get("SECRET_KEY", "dev-secret-key-no-usar-en-produccion")

DEBUG = os.environ.get("DEBUG", "false") == "true"
ALLOWED_HOSTS = ["*"]  # Para pruebas, luego cambia al dominio de Koyeb

if os.environ.get("DATABASE_URL"):
    DATABASES = {
        "default": dj_database_url.config(default=os.environ.get("DATABASE_URL"))
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
    
    import os
import dj_database_url





# Authentication User Model
AUTH_USER_MODEL = 'home.Usuario'


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'inicio_sesion.backends.ClienteBackend', 
    'django.contrib.auth.backends.ModelBackend',
]

# Prioridad de algoritmos de Hashing más fuertes para las nuevas contraseñas
PASSWORD_HASHERS = [
    'django.contrib.auth.hashers.Argon2PasswordHasher',
    'django.contrib.auth.hashers.PBKDF2PasswordHasher'
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

MEDIA_URL = '/Imgproductos/'
MEDIA_ROOT = BASE_DIR / 'Imgproductos'

# Seguridad avanzada para HTTPS producción 
# Usamos DEBUG is False para que sean True solo en producción, evitando errores en desarrollo (HTTP)
SESSION_COOKIE_SECURE = DEBUG is False
CSRF_COOKIE_SECURE = DEBUG is False

# Protección contra ataques de secuencias de comandos entre sitios (XSS)
# (impide que JavaScript acceda a las cookies)
SESSION_COOKIE_HTTPONLY = True
CSRF_COOKIE_HTTPONLY = True