# Generated by Django 5.2.7 on 2025-11-06 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CestaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PROCESANDO', 'Procesando'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('subtotal_importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('coste_entrega', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_importe', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('metodo_pago', models.CharField(choices=[('TARJETA', 'Tarjeta'), ('PAYPAL', 'Paypal'), ('TRANSFERENCIA', 'Transferencia'), ('CONTRA_ENTREGA', 'Contra Entrega')], default='TARJETA', max_length=20)),
                ('tipo_envio', models.CharField(blank=True, max_length=50)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('correo_electronico', models.EmailField(max_length=254)),
                ('telefono', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('departamento', models.CharField(max_length=200)),
                ('seccion', models.CharField(max_length=200)),
                ('fabricante', models.CharField(max_length=200)),
                ('categoria', models.CharField(max_length=200)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('esta_agotado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('corre_electronico', models.EmailField(max_length=200, unique=True)),
                ('clave', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='ItemPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='home.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCestaCompra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_unitario', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cesta_compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='home.cestacompra')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Escaparate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Administrador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UsuarioCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_pago', models.CharField(choices=[('TARJETA', 'Tarjeta'), ('PAYPAL', 'Paypal'), ('TRANSFERENCIA', 'Transferencia'), ('CONTRA_ENTREGA', 'Contra Entrega')], default='TARJETA', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('direccion_envio', models.CharField(max_length=255)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='pedido',
            name='usuario_cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.usuariocliente'),
        ),
        migrations.AddField(
            model_name='cestacompra',
            name='usuario_cliente',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.usuariocliente'),
        ),
    ]
