# Generated by Django 5.2.7 on 2025-11-07 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuariocliente',
            name='metodo_pago',
        ),
        migrations.AddField(
            model_name='producto',
            name='esta_destacado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='usuariocliente',
            name='tipo_envio',
            field=models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('RECOGIDA_TIENDA', 'Recogida Tienda')], default='RECOGIDA_TIENDA', max_length=20),
        ),
        migrations.AddField(
            model_name='usuariocliente',
            name='tipo_pago',
            field=models.CharField(choices=[('PASARELA_PAGO', 'Pasarela Pago'), ('CONTRAREEMBOLSO', 'Contrareembolso')], default='PASARELA_PAGO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], default='PAGADO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='metodo_pago',
            field=models.CharField(choices=[('PASARELA_PAGO', 'Pasarela Pago'), ('CONTRAREEMBOLSO', 'Contrareembolso')], default='PASARELA_PAGO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='tipo_envio',
            field=models.CharField(choices=[('DOMICILIO', 'Domicilio'), ('RECOGIDA_TIENDA', 'Recogida Tienda')], default='RECOGIDA_TIENDA', max_length=20),
        ),
        migrations.AlterField(
            model_name='producto',
            name='categoria',
            field=models.CharField(choices=[('CORTE_Y_PODA', 'Corte Y Poda'), ('LABRANZA_Y_PLANTACION', 'Labranza Y Plantacion'), ('RIEGO_MANUAL', 'Riego Manual'), ('CORTACESPEDES_Y_DESBROZADORAS', 'Cortacespedes Y Desbrozadoras'), ('CORTASETOS_Y_MOTOSIERRAS', 'Cortasetos Y Motosierras'), ('SOPLADORES_Y_TRITURADORES', 'Sopladores Y Trituradores'), ('RIEGO_AUTOMATICO', 'Riego Automatico'), ('MANGUERAS', 'Mangueras'), ('MACETAS_E_INVERNADEROS', 'Macetas E Invernaderos'), ('ABONOS_Y_SUSTRATOS', 'Abonos Y Sustratos'), ('GUANTES_Y_ROPA_PROTECCION', 'Guantes Y Ropa Proteccion'), ('GAFAS_Y_CASCOS', 'Gafas Y Cascos'), ('CUCHILLAS_Y_CADENAS', 'Cuchillas Y Cadenas'), ('BATERIAS_Y_CARGADORES', 'Baterias Y Cargadores'), ('MUEBLES_Y_DECORACION', 'Muebles Y Decoracion'), ('ILUMINACION_EXTERIOR', 'Iluminacion Exterior')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='producto',
            name='seccion',
            field=models.CharField(choices=[('HERRAMIENTAS_MANUALES', 'Herramientas Manuales'), ('MAQUINARIA_DE_JARDÍN', 'Maquinaria De Jardín'), ('RIEGO', 'Riego'), ('CULTIVO_Y_HUERTO', 'Cultivo Y Huerto'), ('PROTECCION_Y_SEGURIDAD', 'Proteccion Y Seguridad'), ('ACCESORIOS_Y_REPUESTOS', 'Accesorios Y Repuestos'), ('JARDÍN_Y_EXTERIOR', 'Jardín Y Exterior')], max_length=50),
        ),
        migrations.DeleteModel(
            name='Escaparate',
        ),
    ]
