# Generated by Django 5.2.7 on 2025-11-07 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_usuariocliente_metodo_pago_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['orden', 'nombre']},
        ),
        migrations.AddField(
            model_name='producto',
            name='orden',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Posición de Ordenación'),
        ),
    ]
