# Generated by Django 5.2.7 on 2025-11-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_producto_options_producto_orden'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='producto',
            options={'ordering': ['orden']},
        ),
        migrations.AlterField(
            model_name='producto',
            name='orden',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
