# Generated by Django 5.2.8 on 2025-11-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_usuario_is_active_usuario_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuariocliente',
            name='last_login',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='usuariocliente',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
