# Generated by Django 4.2.25 on 2025-11-12 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_remove_usuario_clave_alter_usuario_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='static/imagen.avif', null=True, upload_to=''),
        ),
    ]
