# Generated by Django 4.2.25 on 2025-11-12 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_producto_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, default='static/i1.png', null=True, upload_to=''),
        ),
    ]
