# Generated by Django 4.2.25 on 2025-11-14 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_alter_producto_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='cestacompra',
            name='session_id',
            field=models.UUIDField(blank=True, default=None, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='cestacompra',
            name='usuario_cliente',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.usuariocliente'),
        ),
    ]
