# Generated by Django 4.2.25 on 2025-11-16 10:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_cestacompra_session_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='pago',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='direccion_envio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('PEDIDO', 'Pedido'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado')], default='PEDIDO', max_length=20),
        ),
        migrations.AlterField(
            model_name='pedido',
            name='usuario_cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.usuariocliente'),
        ),
    ]
