# Generated by Django 4.2.25 on 2025-11-16 10:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_pedido_pago_alter_pedido_direccion_envio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_hash', models.CharField(max_length=128)),
                ('card_cvv_hash', models.CharField(blank=True, max_length=128, null=True)),
                ('card_expiry', models.CharField(max_length=5)),
                ('ultimos_cuatro', models.CharField(max_length=4)),
                ('usuario_cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarjetas', to='home.usuariocliente')),
            ],
            options={
                'unique_together': {('usuario_cliente', 'card_hash')},
            },
        ),
    ]
