# Generated by Django 4.2.25 on 2025-11-16 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0015_tarjeta'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='tracking_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='ID de seguimiento'),
        ),
    ]
